In [1]:
from process import *
%load_ext autoreload
%autoreload 2

In [2]:
list_view = generate_data()
top_r = 20

A, B = cal_A_B(list_view, top_r)

list_U = []


for i in range(len(B)):
    list_U.append(linearized_bregman(A[i], B[i]))

temp = cov_matrix(list_view, list_U)

0.18763284278062675
0.03167587707877582
0.010437416654856941
0.005425087537025328
0.0027488563617868054
0.0015886855135609666
0.0009373146545725779
0.0007040666124084494
0.0004961273272102163
0.0003499531269907998
0.0003195465176849314
0.00024352216117171758
0.00017413458186088925
0.0001553887603946398
0.00012742262747392024
0.00010730366277373124
9.308904764899989e-05
7.831532799143234e-05
7.093000173327384e-05
5.440916934171828e-05
5.64897571292694e-05
5.271998785841123e-05
4.401333554596403e-05
4.082784338835238e-05
3.7553649678558616e-05
3.2434786853380495e-05
2.6038682505163215e-05
2.166759659972522e-05
2.3712742930856577e-05
2.343203546626855e-05
1.932436610763112e-05
1.6421781554412138e-05
1.6842310856852506e-05
1.5840622536947896e-05
1.3275636165280664e-05
1.2980914233699463e-05
1.2918193284322369e-05
1.2345197818130882e-05
1.054410141423725e-05
0.327227035895647
0.05811620364213952
0.017534773173421298
0.007302444688692776
0.0038486480004513986
0.002423420748132674
0.001406952

In [3]:
cal_sparse(list_U[1])

0.9320333333333334

In [14]:
cov_matrix(list_view=list_view, list_U=list_U)

array([[ 1.00000189e+00, -1.63727987e+17, -1.94714122e+17,
         2.73933447e+16, -2.33033194e+18, -2.47062483e+19,
         6.04969188e+16, -9.18597597e+18, -3.10176578e+17,
        -2.47302584e+18, -5.31878139e+17,  4.30498004e+18,
         2.58193274e+17,  2.44988225e+18,  5.69501592e+19,
         7.61907834e+20, -3.79333562e+18, -5.98414483e+22,
        -3.31224735e+20,  1.24620723e+16],
       [ 1.61727703e+18,  1.00002506e+00, -6.80850588e+15,
         2.13784260e+17,  1.78007654e+17, -3.29685730e+16,
        -3.53033310e+17, -4.89383079e+16, -7.04426935e+15,
        -9.49947257e+17,  4.75781202e+16,  8.54408962e+18,
         1.11622829e+17,  5.97726368e+16,  8.81470934e+17,
         6.37967356e+15, -2.92758025e+16, -6.40026103e+17,
        -1.21048497e+16,  6.74812492e+16],
       [-4.73326343e+17,  3.16406682e+17,  9.99997775e-01,
        -8.00753007e+16,  2.21240756e+17,  6.00654020e+15,
        -7.61806063e+19,  1.70988510e+16,  1.40664126e+16,
         2.08290320e+19,  3.1

In [15]:
from sklearn.metrics import r2_score

In [16]:
left = list_U[0].T.dot(list_view[0])  # (top_r, N)
right = list_U[1].T.dot(list_view[1])

In [18]:
r2_score(right, left)

0.9999999983877619

In [24]:
# 基本上为1，对角线上的元素，所以相关性很高
cov_matrix(list_view, list_U, select=True)

array([1.00000189, 1.00002506, 0.99999778, 0.99999505, 0.9999988 ,
       1.0000198 , 1.0000011 , 1.00000269, 1.00000096, 0.99999354,
       1.00000504, 1.00000586, 0.99999222, 1.00000469, 0.99999933,
       0.9999919 , 0.99999295, 1.00000505, 0.99999937, 1.0000041 ])

# boston数据集

In [13]:
list_view = generate_boston()

In [67]:
list_U = cal_U(list_view, top_r=5)

0.008851049210086137
0.0018759173575385916
0.0008968803408923091
0.0002642301761870049
0.00012191419300235726
0.00012187509197280368
7.783470510020332e-05
5.1033282032721624e-05
2.3655479082813107e-05
2.3655479082731087e-05
2.365547908273135e-05
2.365547908273142e-05

next view: 


next view: 



In [68]:
cal_sparse(list_U[0])

0.0

In [69]:
cal_sparse(list_U[1])

0.8

In [70]:
cov_matrix(list_view, list_U, select=True)

/Users/huojunyi/biss/论文/gcca/process.py:139: RuntimeWarning: divide by zero encountered in true_divide
  temp = up / np.square(down1 * down2)
/Users/huojunyi/biss/论文/gcca/process.py:139: RuntimeWarning: invalid value encountered in true_divide
  temp = up / np.square(down1 * down2)


array([1.01126833,        nan,        nan,        nan,        nan])

In [71]:
from sklearn.metrics import r2_score
def cal_r2_score(list_view, list_U):
    left = list_U[0].T.dot(list_view[0])  # (top_r, N)
    right = list_U[1].T.dot(list_view[1])

    return r2_score(left, right)

In [72]:
cal_r2_score(list_view, list_U)

0.10520970199325629